services:
  vscode:
    build: .
    volumes:
      - ../:/workspace
      # Docker
      - ~/.docker:/mnt/.docker
      # Docker socket to access Docker server
      - /var/run/docker.sock:/var/run/docker.sock
      # SSH directory for Linux, OSX and WSL
      # On Linux and OSX, a symlink /mnt/ssh <-> ~/.ssh is
      # created in the container. On Windows, files are copied
      # from /mnt/ssh to ~/.ssh to fix permissions.
      - ~/.ssh:/mnt/.ssh
      # Shell history persistence
      - ~/.bash_history:/mnt/.bash_history
      # Git config
      - ~/.gitconfig:/mnt/.gitconfig
    environment:
      - TZ=
    entrypoint: ["bash", "-c", "while sleep 1000; do :; done"]
    network_mode: host
